[buildPlans.prasevka]
family = "Prasevka"
spacing = "normal"
serifs = "sans"
no-cv-ss = false
export-glyph-names = true

  [buildPlans.prasevka.variants]
  inherits = "ss08"

    [buildPlans.prasevka.variants.design]
    capital-a = "straight-serifless"
    capital-n = "asymmetric"
    capital-w = "curly"
    capital-x = "curly-serifless"
    capital-y = "curly-serifless"
    f = "flat-hook"
    g = "double-storey-open"
    k = "symmetric-connected-serifless"
    l = "serifed-flat-tailed"
    m = "short-leg"
    n = "straight"
    p = "eared"
    r = "hookless-top-serifed"
    t = "flat-hook-short-neck"
    w = "curly"
    x = "curly-serifless"
    y = "curly-turn"
    z = "straight-serifless"
    zero = "slashed"
    one = "base"
    two = "curly-neck"
    three = "flat-top"
    four = "semi-open"
    five = "oblique-upper-left-bar"
    six = "open-contour"
    seven = "straight-serifed"
    eight = "crossing-asymmetric"
    nine = "straight-bar"
    asterisk = "penta-low"
    underscore = "high"
    paren = "flat-arc"
    brace = "curly-flat-boundary"
    number-sign = "slanted"
    at = "fourfold"
    dollar = "interrupted"
    cent = "bar-interrupted"
    percent = "rings-continuous-slash"
    ascii-single-quote = "straight"
    ascii-grave = "straight"
    question = "smooth"
    punctuation-dot = "round"
    lig-neq = "vertical-dotted"
    lig-equal-chain = "with-notch"

[buildPlans.prasevka.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.prasevka.weights.medium]
shape = 500
menu = 500
css = 500

[buildPlans.prasevka.weights.bold]
shape = 700
menu = 700
css = 700



[buildPlans.prasevka.widths.normal]
shape = 550 # default: 500, min: 434, max: 664
menu  = 5
css   = "normal"

[buildPlans.prasevka.widths.extended]
shape = 630 # default: 576, min: 434, max: 664
menu  = 9
css   = "expanded"

[buildPlans.prasevka.slopes.italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"

[buildPlans.prasevka.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.prasevka.metric-override]
leading = 1300
parenSize = 930
cap = 750
xHeight = 580
