[buildPlans.anosevka]
family = "Anosevka"
spacing = "term"
serifs = "sans"
no-cv-ss = false
export-glyph-names = true

[buildPlans.anosevka.variants]
inherits = "ss05"

[buildPlans.anosevka.variants.design]
capital-a = "straight-serifless"
capital-b = "standard-serifless"
capital-c = "unilateral-inward-serifed"
capital-d = "more-rounded-serifless"
capital-e = "serifless"
capital-f = "serifless"
capital-g = "toothless-corner-serifless-hooked"
capital-h = "serifless"
capital-i = "serifed"
capital-j = "serifed-both-sides"
capital-k = "symmetric-touching-serifless"
capital-l = "serifless"
capital-m = "slanted-sides-hanging"
capital-n = "standard"
capital-p = "closed"
capital-q = "curly-tailed"
capital-r = "straight"
capital-s = "serifless"
capital-t = "serifless"
capital-u = "toothless-rounded"
capital-v = "straight"
capital-w = "straight"
capital-x = "straight-serifless"
capital-y = "straight-serifless"
capital-z = "straight-serifless"
a = "double-storey-serifless"
b = "toothed"
c = "serifless"
d = "toothed-serifless"
e = "flat-crossbar"
f = "flat-hook"
g = "double-storey-open"
h = "straight"
i = "serifed"
j = "serifed"
k = "symmetric-touching-serifless"
l = "tailed-serifed"
m = "normal"
n = "straight"
p = "eared"
q = "straight"
r = "top-serifed"
s = "serifless"
t = "diagonal-tailed"
u = "toothed"
v = "straight"
w = "straight"
x = "straight-serifless"
y = "straight-turn"
z = "straight-serifless"
zero = "slashed"
one = "base"
two = "straight-neck"
three = "flat-top"
four = "closed"
five = "oblique-upper-left-bar"
six = "straight-bar"
seven = "straight-serifed"
eight = "two-circles"
nine = "straight-bar"
tilde = "low"
asterisk = "penta-low"
underscore = "low"
pilcrow = "low"
caret = "high"
paren = "flat-arc"
brace = "curly-flat-boundary"
number-sign = "upright"
ampersand = "closed"
at = "threefold"
dollar = "interrupted"
cent = "through"
percent = "rings-continuous-slash"
bar = "force-upright"
lig-ltgteq = "slanted"
ascii-single-quote = "straight"
ascii-grave = "straight"
question = "smooth"
punctuation-dot = "round"
diacritic-dot = "round"
lig-neq = "vertical-dotted"
lig-equal-chain = "without-notch"

[buildPlans.anosevka.weights.light]
shape = 400
menu = 300
css = 300

[buildPlans.anosevka.weights.regular]
shape = 500
menu = 400
css = 400


[buildPlans.anosevka.weights.bold]
shape = 800
menu = 700
css = 700


[buildPlans.anosevka.widths.normal]
shape = 574    # default: 500, min: 434, max: 664
menu = 5
css = "normal"

[buildPlans.anosevka.widths.extended]
shape = 620      # default: 576, min: 434, max: 664
menu = 7
css = "expanded"

[buildPlans.anosevka.slopes.italic]
angle = 9.6
shape = "italic"
menu = "italic"
css = "italic"

[buildPlans.anosevka.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.anosevka.metric-override]
cap = 780
ascender = 780
xHeight = 600
parenSize = 950
leading = 1300
sb = 65
