[buildPlans.firsevka]
family = "Firsevka"
spacing = "normal"
serifs = "sans"
no-cv-ss = false
export-glyph-names = true

  [buildPlans.firsevka.variants]
  inherits = "ss05"

    [buildPlans.firsevka.variants.design]
    f = "serifless"
    g = "double-storey-open"
    m = "short-leg"
    zero = "slashed"
    paren = "large-contour"
    brace = "curly-flat-boundary"
    number-sign = "slanted"
    ampersand = "closed"
    dollar = "interrupted"
    bar = "force-upright"
    lig-ltgteq = "flat"
    question = "smooth"
    punctuation-dot = "round"
    lig-neq = "vertical-dotted"
    lig-equal-chain = "without-notch"

[buildPlans.firsevka.weights.light]
shape = 300
menu = 300
css = 300

[buildPlans.firsevka.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.firsevka.weights.medium]
shape = 500
menu = 500
css = 500

[buildPlans.firsevka.weights.bold]
shape = 700
menu = 700
css = 700



[buildPlans.firsevka.widths.normal]
shape = 590 # default: 500, min: 434, max: 664
menu  = 5
css   = "normal"

[buildPlans.firsevka.widths.extended]
shape = 615 # default: 576, min: 434, max: 664
menu  = 7
css   = "expanded"

[buildPlans.firsevka.slopes.italic]
angle = 9.5
shape = "italic"
menu = "italic"
css = "italic"

[buildPlans.firsevka.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.firsevka.metric-override]
leading = 1300
parenSize = 930
cap = 750
xHeight = 580



